name: petapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  firebase_auth: ^3.3.16
  firebase_core: ^1.15.0
  persistent_bottom_nav_bar: ^4.0.2
  get_storage: ^2.0.3
  cloud_firestore: ^3.1.15
  font_awesome_flutter: ^10.1.0
  google_maps_flutter: ^2.1.8
  sliding_sheet: ^0.5.2
  google_fonts: ^3.0.1
  carousel_slider: ^4.1.1
  swipe_cards: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/img/
 